version: "3"
services:
    nginx:
        image: nginx:latest
        volumes:
            - './laravel:/var/www/laravel'
            - './_docker/nginx/conf.d:/etc/nginx/conf.d'
        ports:
            - 8876:80
        depends_on:
            - application
        container_name: nginx
    application:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - './laravel:/var/www/laravel'
        depends_on:
            - db
        container_name: app
    db:
        image: mysql:8
        restart: always
        volumes:
            - './mysql_db:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: work
        ports:
            - 8101:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: db
    adminer:
        image: adminer
        ports:
            - 8080:8080